root = "." # The root directory of the project
tmp_dir = "tmp" # The temprary directory where air will store its temporary files

[build]
bin = "main"
cmd = "go build -o {{.Output}} {{.Input}}"
exclude = ["tmp/*", "client/*"]
include = ["**/*.go"]
ignore = ["tmp/*"]
